name: Tag and Release to Production

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary for creating and pushing tags

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and push tag
        run: |
          VERSION="v$(date +%Y.%m.%d.%H%M%S)"
          echo "Generated tag: $VERSION"
          git tag $VERSION
          git remote set-url origin https://x-access-token:${{secrets.GH_PAT}}@github.com/${{ github.repository }}
          git push origin $VERSION
